---
title: "Data Visualization Examples"
author: "Erica Bishop"
format: html
editor: visual
jupyter: python3
---

# Data Visualization Examples

Below are examples of visualizations taken from my various coursework. 

```{r echo=FALSE}
library(spData)
library(leaflegend)
library(leaflet)
library(tidyverse)
library(patchwork)
```

## Spatial data visualization with `leaflet` in R.

The map below shows the world population by country using the `world` data from the `spData` package.

```{r}

pal = colorNumeric(palette = "PuRd", domain = world$pop) #create a color palette

leaflet(data = world) |> #add data
  addPolygons(data = world,
              color = ~pal(pop), #color by population
              fillOpacity = 0.5) |>
  addProviderTiles(providers$OpenStreetMap) |> #add known basemap
  addPolygons(weight = 0.5,
              color = "black") |> 
  addLegendNumeric(pal = pal, #create more intuitive legend
            values = ~pop,
            position = 'topright',
            title = "Population",
            decreasing = TRUE
            ) |> 
  setView(lng = -120, lat = 47, zoom = 3) #toggle where map view starts and zoom

```

## Spatial data visualization with `cartopy` in Python

```{python echo=FALSE}
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import cartopy
import cartopy.crs as ccrs
```

```{python}



```


```{python}

#create color palette - blue shows low and red shows high intensities
palette = [
  '000096','0064ff', '00b4ff', '33db80', '9beb4a',
  'ffeb00', 'ffb300', 'ff6400', 'eb1e00', 'af0000'
]

# set visualization parameters
visParams = {'bands': ['precipitationCal'],
             'min': 0,
             'max': 42,
             'palette': palette,
             'opacity' : 0.5
            }



```

